### ISSUE TITLE
Oral Presentation Availability Picker

### ISSUE THREAD

**Issue by DerekStride** [JFleming4/FourthYearProjectSite#15]
Please no giant matrix, pls?

**Comment by JFleming4** [comment]
Things to do
- [x] Create Oral Presentation Page #39 
- [ ] Create Logic to handle selecting a time that works for one project #40 
- [ ] Extend logic to make sure times are selected for all projects #40 
- [x] Ensure database entries are made to state the availability and when a time is complete #41 
- [ ] Add oral presentation time to project view #63
- [ ] Track selected TimeSlots by user #68
